### PR TITLE
Add verbose option.

### PR DESCRIPTION
**Pull request by andyburke**

### CODE REVIEW

**Comment by anthonyshort** [comment]
This is cool, but I want to see if we can just emit some events and use them as hooks instead of putting the logging throughout the code.

So we can use it something like this:

```
builder.use(verboseLogging);
```

And the builder will emit events like `start`, `file`, `end` etc. that this can hook into. The main reason is just so that it decouples the logging.

**Comment by andyburke** [comment]
Could you point me at an example? I'm fine with it being implemented differently, but I definitely missed having the output so I did the quickest thing to get it back.

**Comment by anthonyshort** [comment]
Yeah no problem, I'll take a look at emitting some events and providing an example

**Comment by kewah** [comment]
Verbose option has been added in the version 0.5.0

**Pull request closed without merging**
