### PR TITLE
Rename task to component_build

### PR DESCRIPTION
**Pull request by bergie**
The current _component_ task clashes with the grunt-component plugin, as described in #16.

### CODE REVIEW

**Comment by anthonyshort** [comment]
What do other people think of this? It could provide fewer conflicts and does make sense, since it is called grunt-component-build 

/cc @kewah

**Comment by kewah** [comment]
@bergie is right, the task should have the same name as the plugin.

**Comment by bergie** [comment]
Thanks! Can you push the new version to NPM?

**Comment by anthonyshort** [comment]
0.2.7 just published!

**Pull request merged**
