### PR TITLE
Update to be compatible with Grunt 0.4.0

### PR DESCRIPTION
**Pull request by kewah**
Hi, 

I added support for the new version of Grunt (see #1).

Thanks!

### CODE REVIEW

**Comment by geddski** [comment]
+1

**Comment by geddski** [comment]
@kewah I'm trying your branch and getting this error:
`Warning: Cannot read property 'property' of undefined Use --force to continue.` 
You seen that? Here's my config:

``` js
component: {
      app: {
        output: 'build',
        styles: true,
        scripts: [ 'app/js/**/*.js' ],
        sourceUrls: true,
        configure: function(builder) {
          builder.use(require("nghtml")({
            webroot: "app",
            module: "app",
            dev: true
          }));
          builder.use(require("component-json")());
        }
      }
    }
```

**Comment by kewah** [comment]
@geddesign I can't reproduce your bug. I tried with different plugins for builder.js (component-json, less, jade and coffee-script) and it works.
Perhaps if you share a sample of your app, I will find why it's not working :)

**Comment by geddski** [comment]
@kewah found the problem, it was an error in the component-json build extension. Grunt's error reporting didn't help much in tracking it down. Thanks!

**Comment by anthonyshort** [comment]
Has grunt 0.4.0 been released yet? I'll merge this in anyway. Anyone looking for a 0.3.x compatible version can just use the previous version.

**Comment by anthonyshort** [comment]
Made this a beta version just until grunt 0.4.0 is released. Grab it as 0.2.0beta

**Pull request merged**
